'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import Image from 'next/image';
type Project={id:string;title:string;updated_at:string};
type Version={id:string;project_id:string;parent_id:string|null;reference_id:string|null;prompt:string;model:string;image_size:string;status:'pending'|'complete'|'failed';created_at:string};
type Reference={id:string;created_at:string};
type Workspace={projects:Project[];projectId:string|null;versions:Version[];references:Reference[];configured:boolean};
const empty:Workspace={projects:[],projectId:null,versions:[],references:[],configured:false};
async function jsonResponse<T>(response:Response):Promise<T>{const value=await response.json();if(!response.ok)throw new Error(value.error||'Studio could not complete the request.');return value as T;}
export function StudioWorkspace(){
 const [data,setData]=useState<Workspace>(empty);const [selected,setSelected]=useState<string|null>(null);
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [busyLabel,setBusyLabel]=useState('Working…');
 const [newTitle,setNewTitle]=useState('');const [naming,setNaming]=useState(false);
 const [draft,setDraft]=useState('');const [mode,setMode]=useState<'fast'|'precise'>('fast');
 const [size,setSize]=useState<'1024x1024'|'1536x1024'|'1024x1536'>('1024x1024');
 const [parent,setParent]=useState<string|null>(null);const [reference,setReference]=useState<string|null>(null);
 const load=useCallback(async(project?:string|null)=>{try{const next=await jsonResponse<Workspace>(await fetch(`/api/studio${project?`?project=${encodeURIComponent(project)}`:''}`,{cache:'no-store'}));setData(next);setSelected(next.projectId);setError('');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{let active=true;fetch('/api/studio',{cache:'no-store'}).then(response=>jsonResponse<Workspace>(response)).then(next=>{if(active){setData(next);setSelected(next.projectId);setLoading(false);}}).catch(error=>{if(active){setError(error.message);setLoading(false);}});return()=>{active=false;};},[]);
 async function createProject(event:React.FormEvent){event.preventDefault();if(!newTitle.trim())return;setBusy(true);try{const result=await jsonResponse<{id:string}>(await fetch('/api/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:newTitle.trim()})}));await load(result.id);setNewTitle('');setNaming(false);setDraft('');setParent(null);setReference(null);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function upload(file:File){
  if(!selected)return;
  if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size<100||file.size>10_485_760){setError('Choose a PNG, JPEG, or WebP image smaller than 10 MB.');return;}
  setBusy(true);setBusyLabel('Uploading reference…');setError('');
  try{
   const prepared=await jsonResponse<{id:string;path:string;token:string;url:string;publishableKey:string}>(await fetch('/api/studio/reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'prepare',projectId:selected,mediaType:file.type,byteSize:file.size})}));
   const {createClient}=await import('@supabase/supabase-js');
   const storage=createClient(prepared.url,prepared.publishableKey,{auth:{persistSession:false,autoRefreshToken:false}}).storage;
   const transferred=await storage.from('aethelios-studio').uploadToSignedUrl(prepared.path,prepared.token,file,{contentType:file.type,upsert:false});
   if(transferred.error)throw new Error('Reference upload failed. Try selecting it again.');
   const response=await jsonResponse<{id:string}>(await fetch('/api/studio/reference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'complete',projectId:selected,id:prepared.id,mediaType:file.type})}));
   setReference(response.id);setParent(null);await load(selected);
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 async function generate(event:React.FormEvent){event.preventDefault();if(!selected||busy)return;setBusy(true);setBusyLabel('Creating image…');setError('');const requestId=crypto.randomUUID();try{await jsonResponse(await fetch('/api/studio',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:requestId,projectId:selected,parentId:parent,referenceId:reference,prompt:draft,mode,size})}));setDraft('');setReference(null);setParent(null);await load(selected);}catch(e){setError((e as Error).message);await load(selected);setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="studio-surface" aria-label="Aethelios Studio">
  <aside className="studio-projects"><div className="studio-section-head"><h2>Projects</h2><button type="button" onClick={()=>setNaming(value=>!value)} disabled={busy}>+ New</button></div>{naming&&<form className="studio-new-project" onSubmit={createProject}><label htmlFor="studio-title">Project name</label><input id="studio-title" value={newTitle} onChange={event=>setNewTitle(event.target.value)} minLength={1} maxLength={80} required autoFocus /><button type="submit" disabled={busy}>Create</button></form>}{loading?<p>Loading Studio…</p>:data.projects.length===0?<p className="muted">Start a project to keep each visual direction together.</p>:<nav aria-label="Studio projects">{data.projects.map(project=><button key={project.id} type="button" className={selected===project.id?'selected':''} onClick={()=>{setParent(null);setReference(null);setLoading(true);void load(project.id);}}>{project.title}</button>)}</nav>}</aside>
  <div className="studio-main">{error&&<p role="alert" className="studio-error">{error}</p>}{!selected?<div className="studio-empty"><p className="eyebrow">A visual workspace</p><h2>Begin with an idea.</h2><p>Generate an image, upload a reference, then refine a saved version through conversation.</p><button className="button" type="button" onClick={()=>setNaming(true)} disabled={busy}>Create project</button></div>:<>
   <div className="studio-section-head"><div><p className="eyebrow">Saved versions</p><h2>{data.projects.find(p=>p.id===selected)?.title}</h2></div><div className="studio-card-actions"><button type="button" onClick={()=>void load(selected)}>Refresh</button><Link href="/app/aethelios" className="text-link">Aethelios Chat ↗</Link></div></div>
   {!data.configured&&<p className="studio-notice">Image generation is awaiting a server model connection. Your projects remain available.</p>}
   <div className="studio-gallery">{data.versions.length===0?<p className="muted">No images yet. Describe your first direction below.</p>:data.versions.map(version=><article className="studio-card" key={version.id}>{version.status==='complete'?<a href={`/api/studio/image?id=${version.id}&kind=version`} target="_blank" rel="noreferrer" aria-label="Open full image"><Image unoptimized width={512} height={512} src={`/api/studio/image?id=${version.id}&kind=version`} alt={version.prompt} /></a>:<div className="studio-placeholder">{version.status==='pending'?'Creating…':'Generation failed'}</div>}<div className="studio-card-copy"><p>{version.prompt}</p><small>{version.model.endsWith('flare')?'Fast':'Precise'} · {version.image_size} · {new Date(version.created_at).toLocaleDateString()}</small>{version.status==='complete'&&<div className="studio-card-actions"><button type="button" onClick={()=>{setParent(version.id);setReference(null);document.getElementById('studio-prompt')?.focus();}}>Refine this</button><a href={`/api/studio/image?id=${version.id}&kind=version`} download={`aethelios-${version.id}.png`}>Open image ↗</a></div>}{version.status==='failed'&&<button className="studio-retry" type="button" onClick={()=>{setDraft(version.prompt);setParent(version.parent_id);setReference(version.reference_id);document.getElementById('studio-prompt')?.focus();}}>Use prompt again</button>}{version.parent_id&&<small>Refines an earlier version</small>}</div></article>)}</div>
   {data.references.length>0&&<div className="studio-references"><p className="eyebrow">Your references</p><div className="studio-reference-list">{data.references.map(item=><button key={item.id} type="button" aria-label={`Use reference from ${new Date(item.created_at).toLocaleDateString()}`} aria-pressed={reference===item.id} disabled={busy} onClick={()=>{setReference(item.id);setParent(null);document.getElementById('studio-prompt')?.focus();}}><Image unoptimized width={72} height={72} src={`/api/studio/image?id=${item.id}&kind=reference`} alt="" /></button>)}</div></div>}
   <form onSubmit={generate} className="studio-composer"><p className="eyebrow">{parent?'Refine saved image':reference?'Create from reference':'New image'}</p>{(parent||reference)&&<div className="studio-source"><Image unoptimized width={48} height={48} src={`/api/studio/image?id=${parent??reference}&kind=${parent?'version':'reference'}`} alt="Selected source" /><span>{parent?'Editing a saved version':'Using your uploaded reference'}</span><button type="button" onClick={()=>{setParent(null);setReference(null);}}>Clear</button></div>}<label htmlFor="studio-prompt">Describe the visual direction</label><textarea id="studio-prompt" value={draft} onChange={e=>setDraft(e.target.value)} minLength={3} maxLength={3000} required placeholder="A considered portrait in soft afternoon light…" disabled={busy}/><div className="studio-controls"><label>Model<select value={mode} onChange={e=>setMode(e.target.value as 'fast'|'precise')} disabled={busy}><option value="fast">Fast exploration</option><option value="precise">Precise detail</option></select></label><label>Format<select value={size} onChange={e=>setSize(e.target.value as typeof size)} disabled={busy}><option value="1024x1024">Square</option><option value="1536x1024">Landscape</option><option value="1024x1536">Portrait</option></select></label><label className="studio-upload">Add reference<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}} /></label><button className="button" type="submit" disabled={busy||!data.configured||draft.trim().length<3}>{busy?busyLabel:'Generate image'}</button></div><p className="muted">One image per request. Your images are private to your account.</p></form>
  </>}</div>
 </section>;
}
