import 'server-only';
import { z } from 'zod';
import { groomingOwner,GroomingError } from './service';
import { openAILook,type GroomingLookProvider } from './provider';
import { styles } from './look-styles';
export async function lookWorkspace(){const {client,person}=await groomingOwner();const [photos,previews]=await Promise.all([client.from('grooming_photos').select('id,view,captured_on,note').eq('person_id',person.id).eq('view','front').order('captured_on',{ascending:false}).limit(30),client.from('grooming_look_previews').select('*').eq('person_id',person.id).order('created_at',{ascending:false}).limit(25)]);if(photos.error||previews.error)throw new GroomingError('My Look is unavailable.',503);return {photos:photos.data??[],previews:previews.data??[]};}
export async function generateLook(raw:unknown,provider:GroomingLookProvider=openAILook){const input=z.object({photoId:z.uuid(),styleId:z.enum(Object.keys(styles) as [keyof typeof styles,...(keyof typeof styles)[]]),consent:z.literal(true)}).parse(raw),{client,person}=await groomingOwner(true),style=styles[input.styleId],id=crypto.randomUUID();
 const photo=await client.from('grooming_photos').select('storage_key,media_type').eq('id',input.photoId).eq('person_id',person.id).eq('view','front').maybeSingle();if(!photo.data)throw new GroomingError('Source photo not found.',404);
 const begin=await client.rpc('grooming_begin_look',{p_id:id,p_photo:input.photoId,p_category:style.category,p_style:input.styleId});if(begin.error||!begin.data)throw new GroomingError('Look generation limit reached or already in progress.',429);
 let key:string|null=null;try{const file=await client.storage.from('grooming-private').download(photo.data.storage_key);if(file.error||!file.data)throw new GroomingError('Photo unavailable.',503);
  const image=await provider.generate({bytes:new Uint8Array(await file.data.arrayBuffer()),type:photo.data.media_type},style.category,input.styleId),auth=(await client.auth.getUser()).data.user?.id;if(!auth)throw new GroomingError('Session expired.',401);
  key=`${auth}/${id}.png`;const upload=await client.storage.from('grooming-looks').upload(key,image,{contentType:'image/png',upsert:false,cacheControl:'private, no-store'});if(upload.error)throw new GroomingError('Concept could not be stored.',503);
  const finish=await client.rpc('grooming_finish_look',{p_id:id,p_status:'complete',p_key:key});if(finish.error||!finish.data)throw new GroomingError('Concept could not be saved.',503);return id;
 }catch(error){if(key)await client.storage.from('grooming-looks').remove([key]);await client.rpc('grooming_finish_look',{p_id:id,p_status:'failed',p_key:null});throw error;}}
export async function saveLook(raw:unknown){const input=z.object({id:z.uuid(),title:z.string().trim().min(3).max(100),note:z.string().trim().max(400)}).parse(raw),{client,person}=await groomingOwner(true);const result=await client.from('grooming_look_previews').update({title:input.title,note:input.note,saved_at:new Date().toISOString()}).eq('person_id',person.id).eq('id',input.id).eq('status','complete').select('id').maybeSingle();if(result.error||!result.data)throw new GroomingError('Concept could not be saved.',409);}
export async function lookBlob(raw:unknown){const id=z.uuid().parse(raw),{client,person}=await groomingOwner();const row=await client.from('grooming_look_previews').select('storage_key').eq('person_id',person.id).eq('id',id).eq('status','complete').maybeSingle();if(!row.data?.storage_key)throw new GroomingError('Concept not found.',404);const image=await client.storage.from('grooming-looks').download(row.data.storage_key);if(image.error||!image.data)throw new GroomingError('Concept unavailable.',503);return image.data;}
export async function deleteLook(raw:unknown){const id=z.uuid().parse(raw),{client,person}=await groomingOwner(true);const row=await client.from('grooming_look_previews').select('storage_key').eq('person_id',person.id).eq('id',id).maybeSingle();if(!row.data)throw new GroomingError('Concept not found.',404);if(row.data.storage_key){const removal=await client.storage.from('grooming-looks').remove([row.data.storage_key]);if(removal.error)throw new GroomingError('Concept image could not be removed.',503);}const result=await client.from('grooming_look_previews').delete().eq('person_id',person.id).eq('id',id);if(result.error)throw new GroomingError('Image removed; history entry needs cleanup.',503);}
