import 'server-only';import { createHash,randomBytes,randomUUID } from 'node:crypto';import { z } from 'zod';import { currentIdentity } from '@/domains/identity/current';import { groomingOwner,GroomingError } from './service';
const id=z.uuid(),hash=(code:string)=>createHash('sha256').update(code).digest('hex');
export async function professionalWorkspace(){const {client,person}=await groomingOwner();const [profile,looks,passes,proposals]=await Promise.all([client.from('grooming_profiles').select('preferred_look,hair_focus,beard_focus,sensitivities,dislikes').eq('person_id',person.id).maybeSingle(),client.from('grooming_look_previews').select('id,title,note,style_id').eq('person_id',person.id).eq('status','complete').not('saved_at','is',null).limit(20),client.from('grooming_professional_passes').select('*').eq('person_id',person.id).order('created_at',{ascending:false}).limit(25),client.from('grooming_service_proposals').select('*').eq('person_id',person.id).order('created_at',{ascending:false}).limit(25)]);if([profile,looks,passes,proposals].some(r=>r.error))throw new GroomingError('Handoffs unavailable.',503);return {profile:profile.data,looks:looks.data??[],passes:passes.data??[],proposals:proposals.data??[]};}
const input=z.object({label:z.string().trim().min(1).max(100),direction:z.boolean(),hair:z.boolean(),beard:z.boolean(),preferences:z.boolean(),avoid:z.boolean(),targetId:z.union([id,z.literal('')]),note:z.string().trim().max(500)});
export async function createProfessionalPass(raw:unknown){const fields=input.parse(raw),{client,person}=await groomingOwner(true);const [profile,target,active]=await Promise.all([client.from('grooming_profiles').select('preferred_look,hair_focus,beard_focus,sensitivities,dislikes').eq('person_id',person.id).maybeSingle(),fields.targetId?client.from('grooming_look_previews').select('title,note,style_id').eq('person_id',person.id).eq('id',fields.targetId).eq('status','complete').not('saved_at','is',null).maybeSingle():Promise.resolve({data:null,error:null}),client.from('grooming_professional_passes').select('id').eq('person_id',person.id).is('revoked_at',null).gt('expires_at',new Date().toISOString()).limit(6)]);if(profile.error||target.error||active.error||fields.targetId&&!target.data)throw new GroomingError('Selected brief unavailable.',503);if((active.data?.length??0)>=5)throw new GroomingError('Revoke an existing pass first.',409);
 const p=profile.data,t=target.data,passId=randomUUID(),code=randomBytes(16).toString('hex');const saved=await client.from('grooming_professional_passes').insert({id:passId,person_id:person.id,label:fields.label,direction:fields.direction?p?.preferred_look??'':'',hair:fields.hair?p?.hair_focus??'':'',beard:fields.beard?p?.beard_focus??'':'',preferences:fields.preferences?p?.sensitivities??'':'',avoid:fields.avoid?p?.dislikes??'':'',target_title:t?t.title||t.style_id:'',target_detail:t?.note??'',note:fields.note,expires_at:new Date(Date.now()+7*86400000-60000).toISOString()});if(saved.error)throw new GroomingError('Pass could not be created.',503);const stored=await client.rpc('grooming_store_pass_code',{p_pass:passId,p_hash:hash(code)});if(stored.error||!stored.data){await client.from('grooming_professional_passes').update({revoked_at:new Date().toISOString()}).eq('id',passId).eq('person_id',person.id);throw new GroomingError('Code could not be secured.',503);}return code;}
export async function revokeProfessionalPass(raw:unknown){const passId=id.parse(raw),{client,person}=await groomingOwner(true);const result=await client.from('grooming_professional_passes').update({revoked_at:new Date().toISOString()}).eq('id',passId).eq('person_id',person.id).is('revoked_at',null).select('id').maybeSingle();if(result.error||!result.data)throw new GroomingError('Pass could not be revoked.',409);}
export async function receivedProfessionalPasses(){const identity=await currentIdentity();if(!identity)throw new GroomingError('Sign in to view a handoff.',401);const [passes,proposals]=await Promise.all([identity.client.from('grooming_professional_passes').select('*').eq('professional_user_id',identity.authUserId).is('revoked_at',null).gt('expires_at',new Date().toISOString()).limit(20),identity.client.from('grooming_service_proposals').select('pass_id,status').eq('professional_user_id',identity.authUserId).limit(20)]);if(passes.error||proposals.error)throw new GroomingError('Handoffs unavailable.',503);return {passes:passes.data??[],proposals:proposals.data??[]};}
export async function claimProfessionalPass(raw:unknown){const code=z.string().regex(/^[0-9a-f]{32}$/).parse(raw),identity=await currentIdentity();if(!identity)throw new GroomingError('Sign in to redeem a pass.',401);const {data,error}=await identity.client.rpc('grooming_claim_pass',{p_hash:hash(code)});if(error||!data)throw new GroomingError('Code expired, unavailable or already redeemed.',409);}
export async function proposeProfessionalService(raw:unknown){const item=z.object({passId:id,date:z.iso.date(),title:z.string().trim().min(3).max(100),detail:z.string().trim().min(3).max(700),returnNote:z.string().trim().max(200)}).parse(raw),identity=await currentIdentity();if(!identity)throw new GroomingError('Sign in to propose a service.',401);const result=await identity.client.rpc('grooming_propose_service',{p_pass:item.passId,p_id:randomUUID(),p_date:item.date,p_title:item.title,p_detail:item.detail,p_return:item.returnNote});if(result.error||!result.data)throw new GroomingError('Pass unavailable or proposal already submitted.',409);}
export async function decideProfessionalService(raw:unknown,accept:boolean){const proposal=id.parse(raw),{client}=await groomingOwner(true);const result=await client.rpc('grooming_decide_service',{p_id:proposal,p_accept:accept});if(result.error||!result.data)throw new GroomingError('Proposal could not be reviewed.',409);}
