import { budgetedFetch } from '@/platform/openai/budget';
import 'server-only';
import { z } from 'zod';
import { GroomingError } from './service';
import { renderImage } from '@/platform/openai/image';
export const assessmentSchema=z.object({usable:z.boolean(),qualityNote:z.string().max(400),summary:z.string().max(1200),nextStep:z.string().max(500),observations:z.array(z.object({area:z.enum(['skin','hair','beard']),description:z.string().min(3).max(400),confidence:z.enum(['low','medium','high'])})).max(9)});
export type Assessment=z.infer<typeof assessmentSchema>;
export interface GroomingAnalysisProvider {analyze(images:{view:string;bytes:Uint8Array;type:string}[],context:string):Promise<Assessment>}
export interface GroomingLookProvider {generate(image:{bytes:Uint8Array;type:string},category:'hair'|'beard',style:string):Promise<Buffer>}
function outputText(output:{type:string;content?:{type:string;text?:string}[]}[]){return output.flatMap(item=>item.content??[]).filter(part=>part.type==='output_text').map(part=>part.text??'').join('');}
export const openAIAnalysis:GroomingAnalysisProvider={async analyze(images,context){
 const key=process.env.OPENAI_API_KEY;if(!key)throw new GroomingError('Ascend Scan is not connected yet.',503);
 const content:[{type:'input_text';text:string},...{type:'input_image';image_url:string}[]]=[{type:'input_text',text:`Assess grooming appearance only. Views in order: ${images.map(i=>i.view).join(', ')}. User-confirmed context: ${context.slice(0,600)}. Return one JSON object with keys usable:boolean, qualityNote:string, summary:string, nextStep:string, observations: array of {area:'skin'|'hair'|'beard',description:string,confidence:'low'|'medium'|'high'}. At most 2 observations per area. Describe only visible appearance; do not infer disease, diagnose, quantify density/pores/dryness, or claim a before/after measurement. If lighting, framing or blur limit interpretation, mark unusable and ask for a retake. Be candid about uncertain views. Recommendations should be practical and not push a purchase. No percentages.`},...images.map(i=>({type:'input_image' as const,image_url:`data:${i.type};base64,${Buffer.from(i.bytes).toString('base64')}`}))];
 const response=await budgetedFetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.AURELIUS_AI_MODEL||'gpt-6-astra',store:false,input:[{role:'user',content}],text:{format:{type:'json_object'}}}),signal:AbortSignal.timeout(120000),cache:'no-store'});
 if(!response.ok)throw new GroomingError('Scan analysis is temporarily unavailable.',response.status===429?429:503);
 const json=await response.json() as {output?:{type:string;content?:{type:string;text?:string}[]}[]};
 try{return assessmentSchema.parse(JSON.parse(outputText(json.output??[])));}catch{throw new GroomingError('Scan analysis could not be interpreted. Try again.',502);}
}};
const directions:Record<string,string>={'tapered-sides':'A restrained haircut with tighter tapered sides and natural length on top','textured-crop':'A low-maintenance textured crop with natural hairline','longer-top':'Preserve greater length and volume on top with shaped sides','short-boxed':'A neat short boxed beard with controlled cheek and neckline','full-tapered':'A fuller beard with carefully tapered sides and preserved chin length','neat-stubble':'Even, neat stubble with a softly defined outline'};
export const openAILook:GroomingLookProvider={generate(image,category,style){const direction=directions[style];if(!direction)throw new GroomingError('Choose a supported look.');return renderImage(`Edit this provided photograph as a concept reference for ${direction}. Change only ${category}. Preserve the person's face, identity, skin, expression, pose, lighting and background. Preserve plausible hair texture and growth. Do not alter facial structure, age or ethnicity. No text or branding. This is a visual concept, not a guaranteed grooming outcome.`,'gpt-image-2.5-sunburst','1024x1024',image);}};
