import 'server-only';
import { z } from 'zod';
import { authorizedPerson } from '@/domains/access/authorize';
import { referenceExtension,referenceType } from '@/domains/studio/image-validation';
export class GroomingError extends Error {constructor(message:string,public status=400){super(message);}}
export async function groomingOwner(write=false){const session=await authorizedPerson(write?'profile.write':'profile.read');if(!session)throw new GroomingError('Sign in to use Grooming Concierge.',401);return session;}
export async function groomingWorkspace(){const {client,person}=await groomingOwner();const id=person.id;
 const [profile,goals,rituals,checkins,products,looks,events,photos]=await Promise.all([
  client.from('grooming_profiles').select('*').eq('person_id',id).maybeSingle(),client.from('grooming_goals').select('*').eq('person_id',id).order('created_at',{ascending:false}).limit(25),
  client.from('grooming_rituals').select('*').eq('person_id',id).order('created_at',{ascending:false}).limit(60),client.from('grooming_checkins').select('*').eq('person_id',id).order('occurred_at',{ascending:false}).limit(60),
  client.from('grooming_products').select('*').eq('person_id',id).order('created_at',{ascending:false}).limit(80),client.from('grooming_looks').select('*').eq('person_id',id).order('created_at',{ascending:false}).limit(60),
  client.from('grooming_events').select('*').eq('person_id',id).order('event_date',{ascending:true}).limit(30),client.from('grooming_photos').select('*').eq('person_id',id).order('captured_on',{ascending:false}).limit(60)]);
 if([profile,goals,rituals,checkins,products,looks,events,photos].some(r=>r.error))throw new GroomingError('Grooming history is temporarily unavailable.',503);
 return {profile:profile.data,goals:goals.data??[],rituals:rituals.data??[],checkins:checkins.data??[],products:products.data??[],looks:looks.data??[],events:events.data??[],photos:photos.data??[]};}
const limited=(n:number)=>z.string().trim().max(n);
const profileInput=z.object({hair_focus:limited(200),beard_focus:limited(200),skin_focus:limited(200),preferred_look:limited(300),effort:z.enum(['simple','considered','detailed']),sensitivities:limited(300),dislikes:limited(300),version:z.coerce.number().int().min(0)});
export async function saveProfile(raw:unknown){const input=profileInput.parse(raw),{client,person}=await groomingOwner(true);const {version,...fields}=input;
 if(version===0){const result=await client.from('grooming_profiles').insert({person_id:person.id,...fields});if(result.error)throw new GroomingError('Profile changed or could not be saved.',409);return;}
 const result=await client.from('grooming_profiles').update(fields).eq('person_id',person.id).eq('version',version).select('version').maybeSingle();if(result.error||!result.data)throw new GroomingError('Profile changed. Reload before saving.',409);}
export async function addGoal(raw:unknown){const input=z.object({title:z.string().trim().min(3).max(160),target_date:z.union([z.iso.date(),z.null()])}).parse(raw),{client,person}=await groomingOwner(true);const result=await client.from('grooming_goals').insert({...input,person_id:person.id});if(result.error)throw new GroomingError('Goal could not be saved.',503);}
export async function finishGoal(raw:unknown){const id=z.uuid().parse(raw),{client,person}=await groomingOwner(true);const result=await client.from('grooming_goals').update({status:'completed'}).eq('person_id',person.id).eq('id',id).eq('status','active').select('id').maybeSingle();if(result.error||!result.data)throw new GroomingError('Goal could not be completed.',409);}
export async function setRitual(raw:unknown){const input=z.object({kind:z.enum(['morning','evening','weekly']),title:z.string().trim().min(3).max(100),steps:z.string().trim().min(3).max(1000)}).parse(raw),{client}=await groomingOwner(true);const result=await client.rpc('grooming_set_ritual',{p_kind:input.kind,p_title:input.title,p_steps:input.steps});if(result.error||!result.data)throw new GroomingError('Ritual could not be saved.',503);}
export async function addCheckin(raw:unknown){const input=z.object({ritual_id:z.uuid(),done:z.boolean(),note:limited(300)}).parse(raw),{client,person}=await groomingOwner(true);const ritual=await client.from('grooming_rituals').select('id').eq('id',input.ritual_id).eq('person_id',person.id).eq('active',true).maybeSingle();if(!ritual.data)throw new GroomingError('Ritual is unavailable.',404);const result=await client.from('grooming_checkins').insert({person_id:person.id,...input});if(result.error)throw new GroomingError('Check-in could not be saved.',503);}
export async function addProduct(raw:unknown){const input=z.object({name:z.string().trim().min(1).max(120),category:z.enum(['hair','beard','skin','other']),relation:z.enum(['owned','tried','favorite','stopped']),shopify_handle:z.union([limited(120),z.null()]),note:limited(400)}).parse(raw),{client,person}=await groomingOwner(true);const result=await client.from('grooming_products').insert({person_id:person.id,...input});if(result.error)throw new GroomingError('Product could not be saved.',503);}
export async function addLook(raw:unknown){const input=z.object({title:z.string().trim().min(3).max(100),detail:limited(700),kind:z.enum(['target','service']),service_date:z.union([z.iso.date(),z.null()])}).parse(raw),{client,person}=await groomingOwner(true);const result=await client.from('grooming_looks').insert({person_id:person.id,...input});if(result.error)throw new GroomingError('Look could not be saved.',503);}
export async function addEvent(raw:unknown){const input=z.object({title:z.string().trim().min(3).max(100),event_date:z.iso.date(),note:limited(300)}).parse(raw),{client,person}=await groomingOwner(true);if(input.event_date<new Date().toISOString().slice(0,10))throw new GroomingError('Choose a future date.');const result=await client.from('grooming_events').insert({person_id:person.id,...input});if(result.error)throw new GroomingError('Occasion could not be saved.',503);}
export async function addPhoto(raw:unknown,file:File,scanId?:string){const input=z.object({view:z.enum(['front','left','right','hair']),captured_on:z.iso.date(),note:limited(300)}).parse(raw),{client,person}=await groomingOwner(true);
 if(!(file instanceof File)||file.size>5242880||file.size<100)throw new GroomingError('Use a JPEG, PNG or WebP image under 5 MB.');const bytes=new Uint8Array(await file.arrayBuffer()),media=referenceType(bytes);if(!media)throw new GroomingError('Image format is not supported.');
 const id=crypto.randomUUID(),auth=(await client.auth.getUser()).data.user?.id;if(!auth)throw new GroomingError('Session expired.',401);const key=`${auth}/${id}.${referenceExtension(media)}`;
 const uploaded=await client.storage.from('grooming-private').upload(key,bytes,{contentType:media,upsert:false,cacheControl:'private, no-store'});if(uploaded.error)throw new GroomingError('Photo could not be stored.',503);
 const saved=await client.from('grooming_photos').insert({id,person_id:person.id,scan_id:scanId??null,storage_key:key,view:input.view,note:input.note,captured_on:input.captured_on,media_type:media,byte_size:bytes.length});
 if(saved.error){await client.storage.from('grooming-private').remove([key]);throw new GroomingError('Photo record could not be saved.',503);}return id;}
export async function photoBlob(raw:unknown){const id=z.uuid().parse(raw),{client,person}=await groomingOwner();const row=await client.from('grooming_photos').select('storage_key').eq('person_id',person.id).eq('id',id).maybeSingle();if(!row.data)throw new GroomingError('Photo not found.',404);const image=await client.storage.from('grooming-private').download(row.data.storage_key);if(image.error||!image.data)throw new GroomingError('Photo unavailable.',503);return image.data;}
export async function deletePhoto(raw:unknown){const id=z.uuid().parse(raw),{client,person}=await groomingOwner(true);const row=await client.from('grooming_photos').select('storage_key').eq('person_id',person.id).eq('id',id).maybeSingle();if(!row.data)throw new GroomingError('Photo not found.',404);const removed=await client.storage.from('grooming-private').remove([row.data.storage_key]);if(removed.error)throw new GroomingError('Photo file could not be removed.',503);const deleted=await client.from('grooming_photos').delete().eq('person_id',person.id).eq('id',id);if(deleted.error)throw new GroomingError('Photo file removed; history entry needs cleanup.',503);}
