'use client';
import { useEffect,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
const views=['front','left','right','hair'] as const;
export function GuidedScan(){const router=useRouter(),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),[index,setIndex]=useState(0),[photos,setPhotos]=useState<Partial<Record<typeof views[number],File>>>({}),[preview,setPreview]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[consent,setConsent]=useState(false);
 useEffect(()=>{return()=>{stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 async function start(){setError('');try{stream.current?.getTracks().forEach(t=>t.stop());stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280}},audio:false});if(video.current)video.current.srcObject=stream.current;}catch{setError('Camera unavailable. Use the upload option below.');}}
 async function capture(){if(!video.current?.videoWidth)return;const canvas=document.createElement('canvas'),scale=Math.min(1,960/video.current.videoWidth);canvas.width=Math.round(video.current.videoWidth*scale);canvas.height=Math.round(video.current.videoHeight*scale);canvas.getContext('2d')?.drawImage(video.current,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,'image/jpeg',.79));if(blob)select(new File([blob],`${views[index]}.jpg`,{type:'image/jpeg'}));}
 async function select(file:File){if(file.size>1200000){setError('Choose an image under 1.2 MB or use the camera capture.');return;}setError('');setPhotos(p=>({...p,[views[index]!]:file}));if(preview)URL.revokeObjectURL(preview);setPreview(URL.createObjectURL(file));}
 async function submit(){if(!photos.front||!photos.left||!photos.right||!consent)return;setBusy(true);setError('');const form=new FormData();for(const view of views)if(photos[view])form.append(view,photos[view]!);form.set('consent','yes');try{const response=await fetch('/api/grooming/scan',{method:'POST',body:form});const body=await response.json();if(!response.ok)throw new Error(body.error||'Assessment unavailable.');router.refresh();router.push('/app/grooming/scan?result=saved#history');}catch(e){setError(e instanceof Error?e.message:'Assessment unavailable.');}finally{setBusy(false);}}
 return <div className="groom-panel groom-form"><p className="eyebrow">Ascend Scan / {index+1} of 4</p><h3>{index===0?'Face the lens.':index===1?'Turn to your left.':index===2?'Turn to your right.':'Hair / scalp, if useful.'}</h3><p>Stand in even daylight, remove filters, keep the camera at eye level and the same distance for each view. A mirror guide helps framing; it does not measure your face.</p><div className="groom-camera"><video ref={video} autoPlay playsInline muted aria-label="Camera preview"/>{preview&&<Image src={preview} alt={`${views[index]} image selected`} className="groom-camera-preview" width={720} height={420} unoptimized/>}<div className="groom-camera-guide" aria-hidden="true"/></div><div className="groom-actions"><button type="button" className="secondary-button" onClick={start}>Start camera</button><button type="button" className="button" onClick={capture}>Capture this view</button><label className="secondary-button">Choose photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void select(file);}} style={{maxWidth:160}}/></label></div><div className="groom-actions">{views.map((view,i)=><button type="button" key={view} onClick={()=>{setIndex(i);if(preview)URL.revokeObjectURL(preview);setPreview(photos[view]?URL.createObjectURL(photos[view]):null);}} className={index===i?'button':'secondary-button'}>{view} {photos[view]?'✓':''}</button>)}</div><label className="groom-inline-check"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>Send these selected images to OpenAI for a qualitative grooming assessment. Stored scan photos remain private in Gent Ascend; you can delete them with the scan.</label><button type="button" className="button" disabled={!photos.front||!photos.left||!photos.right||!consent||busy} onClick={submit}>{busy?'Assessing your selected views…':'Assess selected views'}</button>{error&&<p role="alert">{error}</p>}<small>The assessment is appearance guidance, not a diagnosis. Lighting and angles can change what appears visible.</small></div>;
}
