import Link from 'next/link';
import { cookies } from 'next/headers';
import { requireLocalHarness } from '@/domains/development/guard';
import { currentIdentity } from '@/domains/identity/current';
import { defaultScenario, founderAuthId, readScenario } from '@/domains/development/scenario';
import { currentAccess } from '@/domains/access/current';
import { enterFounder, updateScenario } from './actions';
export default async function DeveloperConsole({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | undefined>>;
}) {
  const env = await requireLocalHarness();
  const identity = await currentIdentity();
  const params = await searchParams;
  const founder = identity?.authUserId === founderAuthId;
  const scenario =
    readScenario((await cookies()).get('aurelius-scenario')?.value, env.AURELIUS_DEV_TOKEN!) ??
    defaultScenario;
  const access = founder ? await currentAccess() : new Set<string>();
  return (
    <main className="console">
      <Link href="/">← Return to Command</Link>
      <p className="eyebrow">Local development only</p>
      <h1>Developer console</h1>
      {params.error && (
        <p role="alert">
          {params.error === 'database'
            ? 'Local account unavailable. Start Supabase and run npm run dev:setup.'
            : 'Entry or scenario could not be verified. Please try again.'}
        </p>
      )}
      {params.saved && <p role="status">Scenario saved.</p>}
      {!founder ? (
        <form action={enterFounder}>
          <h2>Founder access</h2>
          <p>
            Use the local token generated by <code>npm run dev:setup</code>. This signs into the
            seeded Supabase account.
          </p>
          <label htmlFor="token">Local entry token</label>
          <input id="token" name="token" type="password" required autoComplete="off" />
          <button className="button" type="submit">
            Enter as founder
          </button>
        </form>
      ) : (
        <>
          <p>Verified local founder · real Supabase session · owner RLS</p>
          <form action={updateScenario}>
            <label htmlFor="membership">Membership scenario</label>
            <select id="membership" name="membership" defaultValue={scenario.membership}>
              {['founder', 'free', 'aurelius', 'health', 'beta', 'admin'].map((x) => (
                <option key={x}>{x}</option>
              ))}
            </select>
            <label htmlFor="billing">Billing simulation</label>
            <select id="billing" name="billing" defaultValue={scenario.billing}>
              {['none', 'trialing', 'active', 'past_due', 'canceled'].map((x) => (
                <option key={x}>{x}</option>
              ))}
            </select>
            <label className="check">
              <input name="onboarded" type="checkbox" defaultChecked={scenario.onboarded} />{' '}
              Onboarding complete (scenario only)
            </label>
            <button type="submit" className="button">
              Apply scenario
            </button>
          </form>
          <section className="panel">
            <h2>Effective capabilities</h2>
            <ul>
              {[...access].map((x) => (
                <li key={x}>{x}</li>
              ))}
            </ul>
            <p>
              Admin simulation does not grant administrative data access. Clinical authorization is
              never granted by a scenario.
            </p>
          </section>
        </>
      )}
      <section className="panel">
        <h2>Next controls</h2>
        <p>
          History personas, feature switches and memory reset will activate with their corresponding
          modules. Reset the local synthetic database with <code>npm run db:reset</code>.
        </p>
      </section>
    </main>
  );
}
