-- Grooming is a person-owned domain. Generated imagery is never progress evidence.
alter table public.grooming_profiles
 add column preferred_look text not null default '' check(length(preferred_look)<=300),
 add column effort text not null default 'simple' check(effort in ('simple','considered','detailed')),
 add column sensitivities text not null default '' check(length(sensitivities)<=300),
 add column dislikes text not null default '' check(length(dislikes)<=300);
grant insert(preferred_look,effort,sensitivities,dislikes) on public.grooming_profiles to authenticated;
grant update(preferred_look,effort,sensitivities,dislikes) on public.grooming_profiles to authenticated;
create table public.grooming_goals(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.persons(id) on delete cascade,title text not null check(length(title) between 3 and 160),target_date date,status text not null default 'active' check(status in ('active','completed','archived')),created_at timestamptz not null default now());
create table public.grooming_rituals(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.persons(id) on delete cascade,kind text not null check(kind in ('morning','evening','weekly')),title text not null check(length(title) between 3 and 100),steps text not null check(length(steps) between 3 and 1000),version integer not null default 1,active boolean not null default true,created_at timestamptz not null default now(),unique(person_id,kind,version),unique(person_id,id));
create unique index grooming_active_ritual on public.grooming_rituals(person_id,kind) where active;
create table public.grooming_checkins(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.persons(id) on delete cascade,ritual_id uuid not null,done boolean not null, note text not null default '' check(length(note)<=300),occurred_at timestamptz not null default now(),foreign key(person_id,ritual_id) references public.grooming_rituals(person_id,id) on delete cascade);
create table public.grooming_products(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.persons(id) on delete cascade,name text not null check(length(name) between 1 and 120),category text not null check(category in ('hair','beard','skin','other')),relation text not null check(relation in ('owned','tried','favorite','stopped')),shopify_handle text,note text not null default '' check(length(note)<=400),created_at timestamptz not null default now());
create table public.grooming_looks(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.persons(id) on delete cascade,title text not null check(length(title) between 3 and 100),detail text not null default '' check(length(detail)<=700),kind text not null check(kind in ('target','service')),service_date date,created_at timestamptz not null default now());
create table public.grooming_events(id uuid primary key default gen_random_uuid(),person_id uuid not null references public.persons(id) on delete cascade,title text not null check(length(title) between 3 and 100),event_date date not null,note text not null default '' check(length(note)<=300),created_at timestamptz not null default now());
create table public.grooming_scans(id uuid primary key,person_id uuid not null references public.persons(id) on delete cascade,status text not null default 'pending' check(status in ('pending','complete','rejected','failed')),consented_at timestamptz not null default now(),created_at timestamptz not null default now(),completed_at timestamptz,provider_version text,quality_note text not null default '',summary text not null default '',next_step text not null default '',unique(person_id,id));
create table public.grooming_scan_usage(id uuid primary key,person_id uuid not null references public.persons(id) on delete cascade,created_at timestamptz not null default now());
create table public.grooming_photos(id uuid primary key,person_id uuid not null references public.persons(id) on delete cascade,scan_id uuid,storage_key text not null unique,view text not null check(view in ('front','left','right','hair')),note text not null default '' check(length(note)<=300),captured_on date not null,media_type text not null check(media_type in ('image/jpeg','image/png','image/webp')),byte_size integer not null check(byte_size between 100 and 5242880),created_at timestamptz not null default now(),unique(person_id,id),foreign key(person_id,scan_id) references public.grooming_scans(person_id,id) on delete set null (scan_id));
create table public.grooming_scan_observations(id uuid primary key default gen_random_uuid(),person_id uuid not null,scan_id uuid not null,area text not null check(area in ('skin','hair','beard')),description text not null check(length(description) between 3 and 400),confidence text not null check(confidence in ('low','medium','high')),source_version text not null,created_at timestamptz not null default now(),foreign key(person_id,scan_id) references public.grooming_scans(person_id,id) on delete cascade);
create table public.grooming_look_previews(id uuid primary key,person_id uuid not null references public.persons(id) on delete cascade,source_photo_id uuid,category text not null check(category in ('hair','beard')),style_id text not null,title text not null default '' check(length(title)<=100),note text not null default '' check(length(note)<=400),saved_at timestamptz,status text not null default 'pending' check(status in ('pending','complete','failed')),storage_key text unique,created_at timestamptz not null default now(),foreign key(person_id,source_photo_id) references public.grooming_photos(person_id,id) on delete set null (source_photo_id),check(saved_at is null or status='complete'));
create table public.grooming_look_usage(id uuid primary key,person_id uuid not null references public.persons(id) on delete cascade,created_at timestamptz not null default now());
create table public.grooming_professional_passes(id uuid primary key,person_id uuid not null references public.persons(id) on delete cascade,professional_user_id uuid references auth.users(id) on delete set null,label text not null check(length(label) between 1 and 100),direction text not null default '',hair text not null default '',beard text not null default '',preferences text not null default '',avoid text not null default '',target_title text not null default '',target_detail text not null default '',note text not null default '' check(length(note)<=500),created_at timestamptz not null default now(),expires_at timestamptz not null,claimed_at timestamptz,revoked_at timestamptz,check(expires_at>created_at and expires_at<=created_at+interval '7 days'),unique(person_id,id));
create table public.grooming_professional_codes(pass_id uuid primary key references public.grooming_professional_passes(id) on delete cascade,code_hash text not null unique check(code_hash ~ '^[0-9a-f]{64}$'));
create table public.grooming_service_proposals(id uuid primary key,pass_id uuid not null unique,person_id uuid not null,professional_user_id uuid not null references auth.users(id),service_date date not null,title text not null check(length(title) between 3 and 100),detail text not null check(length(detail) between 3 and 700),return_note text not null default '' check(length(return_note)<=200),status text not null default 'pending' check(status in ('pending','accepted','declined')),created_at timestamptz not null default now(),decided_at timestamptz,foreign key(person_id,pass_id) references public.grooming_professional_passes(person_id,id) on delete cascade);
create index grooming_goals_recent on public.grooming_goals(person_id,created_at desc);
create index grooming_rituals_recent on public.grooming_rituals(person_id,created_at desc);
create index grooming_photos_recent on public.grooming_photos(person_id,captured_on desc);
create index grooming_scans_recent on public.grooming_scans(person_id,created_at desc);
create index grooming_previews_recent on public.grooming_look_previews(person_id,created_at desc);
create index grooming_passes_owner on public.grooming_professional_passes(person_id,created_at desc);
create index grooming_passes_recipient on public.grooming_professional_passes(professional_user_id,expires_at) where revoked_at is null;
-- Explicit grants and independent ownership policies. No direct mutation of model results or proposed service.
do $$ declare t text; begin foreach t in array array['grooming_goals','grooming_rituals','grooming_checkins','grooming_products','grooming_looks','grooming_events','grooming_scans','grooming_scan_usage','grooming_photos','grooming_scan_observations','grooming_look_previews','grooming_look_usage','grooming_professional_passes','grooming_professional_codes','grooming_service_proposals'] loop execute format('alter table public.%I enable row level security',t);execute format('revoke all on public.%I from public,anon,authenticated',t);end loop;end $$;
do $$ declare t text; begin foreach t in array array['grooming_goals','grooming_rituals','grooming_checkins','grooming_products','grooming_looks','grooming_events','grooming_scans','grooming_photos','grooming_scan_observations','grooming_look_previews'] loop
 execute format('grant select on public.%I to authenticated',t);
 execute format('create policy %I on public.%I for select to authenticated using(person_id in (select id from public.persons where auth_user_id=(select auth.uid())))',t||'_owner_read',t);
 end loop;end $$;
grant insert on public.grooming_goals,public.grooming_checkins,public.grooming_products,public.grooming_looks,public.grooming_events,public.grooming_photos to authenticated;
do $$ declare t text; begin foreach t in array array['grooming_goals','grooming_checkins','grooming_products','grooming_looks','grooming_events','grooming_photos'] loop
 execute format('create policy %I on public.%I for insert to authenticated with check(person_id in (select id from public.persons where auth_user_id=(select auth.uid())))',t||'_owner_insert',t);
 end loop;end $$;
grant update(status) on public.grooming_goals to authenticated;
create policy grooming_goals_owner_update on public.grooming_goals for update to authenticated using(person_id in(select id from public.persons where auth_user_id=(select auth.uid()))) with check(person_id in(select id from public.persons where auth_user_id=(select auth.uid())));
grant delete on public.grooming_photos,public.grooming_scans,public.grooming_look_previews to authenticated;
do $$ declare t text; begin foreach t in array array['grooming_photos','grooming_scans','grooming_look_previews'] loop execute format('create policy %I on public.%I for delete to authenticated using(person_id in(select id from public.persons where auth_user_id=(select auth.uid())))',t||'_owner_delete',t);end loop;end $$;
grant update(title,note,saved_at) on public.grooming_look_previews to authenticated;
create policy grooming_previews_owner_update on public.grooming_look_previews for update to authenticated using(person_id in(select id from public.persons where auth_user_id=(select auth.uid()))) with check(person_id in(select id from public.persons where auth_user_id=(select auth.uid())));
grant select,insert on public.grooming_professional_passes to authenticated;
grant update(revoked_at) on public.grooming_professional_passes to authenticated;
create policy grooming_pass_owner_read on public.grooming_professional_passes for select to authenticated using(person_id in(select id from public.persons where auth_user_id=(select auth.uid())));
create policy grooming_pass_recipient_read on public.grooming_professional_passes for select to authenticated using(professional_user_id=(select auth.uid()) and revoked_at is null and expires_at>now());
create policy grooming_pass_owner_insert on public.grooming_professional_passes for insert to authenticated with check(person_id in(select id from public.persons where auth_user_id=(select auth.uid())) and professional_user_id is null and claimed_at is null and revoked_at is null and expires_at<=now()+interval '7 days');
create policy grooming_pass_owner_revoke on public.grooming_professional_passes for update to authenticated using(person_id in(select id from public.persons where auth_user_id=(select auth.uid()))) with check(person_id in(select id from public.persons where auth_user_id=(select auth.uid())) and revoked_at is not null);
grant select on public.grooming_service_proposals to authenticated;
create policy grooming_proposal_owner_read on public.grooming_service_proposals for select to authenticated using(person_id in(select id from public.persons where auth_user_id=(select auth.uid())));
create policy grooming_proposal_author_read on public.grooming_service_proposals for select to authenticated using(professional_user_id=(select auth.uid()) and exists(select 1 from public.grooming_professional_passes p where p.id=pass_id and p.professional_user_id=(select auth.uid()) and p.revoked_at is null and p.expires_at>now()));
-- Atomic ritual versioning and owner-only provider writes.
create function public.grooming_set_ritual(p_kind text,p_title text,p_steps text) returns uuid language plpgsql security definer set search_path='' as $$ declare v_person uuid;v_version integer;v_id uuid; begin
 select id into v_person from public.persons where auth_user_id=(select auth.uid());
 if v_person is null or p_kind not in ('morning','evening','weekly') or length(trim(p_title)) not between 3 and 100 or length(trim(p_steps)) not between 3 and 1000 then raise exception 'Invalid ritual';end if;
 perform pg_advisory_xact_lock(hashtextextended(v_person::text||p_kind,102));
 select coalesce(max(version),0)+1 into v_version from public.grooming_rituals where person_id=v_person and kind=p_kind;
 update public.grooming_rituals set active=false where person_id=v_person and kind=p_kind and active;
 insert into public.grooming_rituals(person_id,kind,title,steps,version) values(v_person,p_kind,trim(p_title),trim(p_steps),v_version) returning id into v_id;return v_id;end $$;
create function public.grooming_begin_scan(p_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ declare v_person uuid;begin
 select id into v_person from public.persons where auth_user_id=(select auth.uid());if v_person is null then return false;end if;
 perform pg_advisory_xact_lock(hashtextextended(v_person::text,103));
 if (select count(*) from public.grooming_scan_usage where person_id=v_person and created_at>now()-interval '1 day')>=3 then return false;end if;
 insert into public.grooming_scans(id,person_id) values(p_id,v_person) on conflict do nothing;if not found then return false;end if;
 insert into public.grooming_scan_usage(id,person_id) values(p_id,v_person);return true;end $$;
create function public.grooming_finish_scan(p_id uuid,p_status text,p_quality text,p_summary text,p_next text,p_observations jsonb) returns boolean language plpgsql security definer set search_path='' as $$ declare v_person uuid;v_item jsonb;begin
 select id into v_person from public.persons where auth_user_id=(select auth.uid());
 if v_person is null or p_status not in ('complete','rejected','failed') or length(coalesce(p_quality,''))>400 or length(coalesce(p_summary,''))>1200 or length(coalesce(p_next,''))>500 or jsonb_typeof(p_observations)<>'array' or jsonb_array_length(p_observations)>9 then return false;end if;
 update public.grooming_scans set status=p_status,quality_note=p_quality,summary=p_summary,next_step=p_next,provider_version='openai-qualitative-v1',completed_at=now() where id=p_id and person_id=v_person and status='pending';if not found then return false;end if;
 for v_item in select value from jsonb_array_elements(p_observations) loop
 if (v_item->>'area') not in ('skin','hair','beard') or (v_item->>'confidence') not in ('low','medium','high') or length(v_item->>'description') not between 3 and 400 then raise exception 'Invalid observation';end if;
 insert into public.grooming_scan_observations(person_id,scan_id,area,description,confidence,source_version) values(v_person,p_id,v_item->>'area',v_item->>'description',v_item->>'confidence','openai-qualitative-v1');end loop;return true;end $$;
create function public.grooming_begin_look(p_id uuid,p_photo uuid,p_category text,p_style text) returns boolean language plpgsql security definer set search_path='' as $$ declare v_person uuid;begin
 select id into v_person from public.persons where auth_user_id=(select auth.uid());if v_person is null or not exists(select 1 from public.grooming_photos where person_id=v_person and id=p_photo and view='front') or (p_category,p_style) not in (('hair','tapered-sides'),('hair','textured-crop'),('hair','longer-top'),('beard','short-boxed'),('beard','full-tapered'),('beard','neat-stubble')) then return false;end if;
 perform pg_advisory_xact_lock(hashtextextended(v_person::text,104));
 if (select count(*) from public.grooming_look_usage where person_id=v_person and created_at>now()-interval '1 day')>=4 or exists(select 1 from public.grooming_look_previews where person_id=v_person and status='pending' and created_at>now()-interval '5 minutes') then return false;end if;
 insert into public.grooming_look_previews(id,person_id,source_photo_id,category,style_id) values(p_id,v_person,p_photo,p_category,p_style) on conflict do nothing;if not found then return false;end if;
 insert into public.grooming_look_usage(id,person_id) values(p_id,v_person);return true;end $$;
create function public.grooming_finish_look(p_id uuid,p_status text,p_key text default null) returns boolean language plpgsql security definer set search_path='' as $$ declare v_person uuid;begin
 select id into v_person from public.persons where auth_user_id=(select auth.uid());if v_person is null or p_status not in ('complete','failed') or (p_status='complete' and p_key is distinct from (select auth.uid())::text||'/'||p_id::text||'.png') or (p_status='failed' and p_key is not null) then return false;end if;
 update public.grooming_look_previews set status=p_status,storage_key=p_key where id=p_id and person_id=v_person and status='pending';return found;end $$;
create function public.grooming_store_pass_code(p_pass uuid,p_hash text) returns boolean language plpgsql security definer set search_path='' as $$begin
 if (select auth.uid()) is null or p_hash !~ '^[0-9a-f]{64}$' then return false;end if;
 insert into public.grooming_professional_codes(pass_id,code_hash) select p.id,p_hash from public.grooming_professional_passes p join public.persons owner on owner.id=p.person_id where p.id=p_pass and owner.auth_user_id=(select auth.uid()) and p.professional_user_id is null and p.revoked_at is null and p.expires_at>now() on conflict do nothing;return found;end $$;
create function public.grooming_claim_pass(p_hash text) returns uuid language plpgsql security definer set search_path='' as $$declare v_pass uuid;begin
 if (select auth.uid()) is null or p_hash !~ '^[0-9a-f]{64}$' then return null;end if;
 update public.grooming_professional_passes p set professional_user_id=(select auth.uid()),claimed_at=now() from public.grooming_professional_codes c where c.pass_id=p.id and c.code_hash=p_hash and p.professional_user_id is null and p.revoked_at is null and p.expires_at>now() and not exists(select 1 from public.persons owner where owner.id=p.person_id and owner.auth_user_id=(select auth.uid())) returning p.id into v_pass;return v_pass;end $$;
create function public.grooming_propose_service(p_pass uuid,p_id uuid,p_date date,p_title text,p_detail text,p_return text) returns boolean language plpgsql security definer set search_path='' as $$declare v_person uuid;begin
 if (select auth.uid()) is null or p_date is null or p_date>current_date or p_date<current_date-interval '2 years' or length(trim(p_title)) not between 3 and 100 or length(trim(p_detail)) not between 3 and 700 or length(coalesce(p_return,''))>200 then return false;end if;
 select person_id into v_person from public.grooming_professional_passes where id=p_pass and professional_user_id=(select auth.uid()) and revoked_at is null and expires_at>now() for update;if v_person is null then return false;end if;
 insert into public.grooming_service_proposals(id,pass_id,person_id,professional_user_id,service_date,title,detail,return_note) values(p_id,p_pass,v_person,(select auth.uid()),p_date,trim(p_title),trim(p_detail),coalesce(p_return,'')) on conflict do nothing;return found;end $$;
create function public.grooming_decide_service(p_id uuid,p_accept boolean) returns boolean language plpgsql security definer set search_path='' as $$declare v public.grooming_service_proposals%rowtype;begin
 if (select auth.uid()) is null or p_accept is null then return false;end if;
 select s.* into v from public.grooming_service_proposals s join public.persons owner on owner.id=s.person_id where s.id=p_id and s.status='pending' and owner.auth_user_id=(select auth.uid()) for update of s;if not found then return false;end if;
 if p_accept then insert into public.grooming_looks(id,person_id,title,detail,kind,service_date) values(v.id,v.person_id,v.title,left(v.detail||case when v.return_note<>'' then E'\nSuggested return: '||v.return_note else '' end,700),'service',v.service_date);end if;
 update public.grooming_service_proposals set status=case when p_accept then 'accepted' else 'declined' end,decided_at=now() where id=p_id;return true;end $$;
revoke all on function public.grooming_set_ritual(text,text,text),public.grooming_begin_scan(uuid),public.grooming_finish_scan(uuid,text,text,text,text,jsonb),public.grooming_begin_look(uuid,uuid,text,text),public.grooming_finish_look(uuid,text,text),public.grooming_store_pass_code(uuid,text),public.grooming_claim_pass(text),public.grooming_propose_service(uuid,uuid,date,text,text,text),public.grooming_decide_service(uuid,boolean) from public,anon;
grant execute on function public.grooming_set_ritual(text,text,text),public.grooming_begin_scan(uuid),public.grooming_finish_scan(uuid,text,text,text,text,jsonb),public.grooming_begin_look(uuid,uuid,text,text),public.grooming_finish_look(uuid,text,text),public.grooming_store_pass_code(uuid,text),public.grooming_claim_pass(text),public.grooming_propose_service(uuid,uuid,date,text,text,text),public.grooming_decide_service(uuid,boolean) to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('grooming-private','grooming-private',false,5242880,array['image/jpeg','image/png','image/webp']),('grooming-looks','grooming-looks',false,10485760,array['image/png']) on conflict(id) do nothing;
create policy grooming_private_read on storage.objects for select to authenticated using(bucket_id in ('grooming-private','grooming-looks') and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy grooming_private_insert on storage.objects for insert to authenticated with check(bucket_id in ('grooming-private','grooming-looks') and (storage.foldername(name))[1]=(select auth.uid())::text);
create policy grooming_private_delete on storage.objects for delete to authenticated using(bucket_id in ('grooming-private','grooming-looks') and (storage.foldername(name))[1]=(select auth.uid())::text);
